openapi: 3.0.1
info:
  title: Nimbus - Api Documentation
  description: Nimbus services
  contact: {}
  version: 3.0.0
servers:
  - url: https://nimbus.northernarc.com/notifications
    description: Generated server url

tags:
  - name: ValueFirst - SMS
    description: ValueFirst - SMS
paths:
  /api/notification/vf/token/disable:
    get:
      tags:
        - ValueFirst - SMS
      description: 'Disable Token : Value -> Token/All'
      operationId: disableToken
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/notification/vf/token/active:
    get:
      tags:
        - ValueFirst - SMS
      description: Get Active Token
      operationId: getActiveToken
      parameters:
        - name: credentialId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    JsonNode:
      type: object
    ReportConfig:
      type: object
      properties:
        dbClientId:
          type: string
        query:
          type: string
        fileName:
          type: string
        typeId:
          type: integer
          description: Please enter the notification type id applicable for your request
          format: int64
        format:
          type: string
          description: >-
            Format field can have any one of the following values:
            CSV,XLSX,PDF,HTML
    ReportHelper:
      type: object
      properties:
        reportConfigs:
          type: array
          items:
            $ref: '#/components/schemas/ReportConfig'
        toUserEmails:
          type: array
          items:
            type: string
        ccUserEmails:
          type: array
          items:
            type: string
        bccUserEmails:
          type: array
          items:
            type: string
        typeId:
          type: integer
          description: Please enter the notification type id applicable for your request
          format: int64
        notificationContent:
          $ref: '#/components/schemas/JsonNode'
        isNotification:
          type: boolean
    Attachment:
      type: object
      properties:
        fileName:
          type: string
        fileExtension:
          type: string
        file:
          type: string
          format: binary
        fileContentAsBytes:
          type: array
          items:
            type: string
            format: byte
    TemplateHelper:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        appId:
          type: string
        typeId:
          type: integer
          format: int64
        content:
          $ref: '#/components/schemas/JsonNode'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        fromUserEmail:
          type: string
        toUserEmails:
          type: array
          items:
            type: string
        ccUserEmails:
          type: array
          items:
            type: string
        bccUserEmails:
          type: array
          items:
            type: string
        toUserMobileNumbers:
          type: array
          items:
            type: string
        productName:
          type: string
        format:
          type: string
        attachmentAsMail:
          type: boolean
        objectId:
          type: string
    NotificationRoutingUrls:
      type: object
      properties:
        notificationRoutingUrlsId:
          $ref: '#/components/schemas/NotificationRoutingUrlsId'
        apiRoutingUrl:
          type: string
        uiRoutingUrl:
          type: string
        notificationRoutingUrlModel:
          $ref: '#/components/schemas/NotifiedChannel'
    NotificationRoutingUrlsId:
      type: object
      properties:
        channelId:
          type: string
        appId:
          type: string
        notificationId:
          type: integer
          format: int64
    Notifications:
      type: object
      properties:
        createdBy:
          type: integer
          format: int64
        createdDate:
          type: string
          format: date-time
        lastModifiedBy:
          type: integer
          format: int64
        lastModifiedDate:
          type: string
          format: date-time
        notificationId:
          type: integer
          format: int64
        type:
          type: integer
          format: int64
        objectId:
          type: string
        appId:
          type: string
        notifiedToModel:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/NotifiedTo'
        notifiedCcModel:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/NotifiedCc'
        notifiedChannel:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/NotifiedChannel'
    NotifiedCc:
      type: object
      properties:
        notifiedCcId:
          $ref: '#/components/schemas/NotifiedCcId'
        notificationsModel:
          $ref: '#/components/schemas/Notifications'
    NotifiedCcId:
      type: object
      properties:
        notificationId:
          type: integer
          format: int64
        notifiedTo:
          type: string
    NotifiedChannel:
      type: object
      properties:
        notifiedChannelId:
          $ref: '#/components/schemas/NotifiedChannelId'
        subject:
          type: string
        content:
          type: string
        sentOn:
          type: string
          format: date-time
        attachment:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        notificationRoutingUrls:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/NotificationRoutingUrls'
        notificationsModel:
          $ref: '#/components/schemas/Notifications'
    NotifiedChannelId:
      type: object
      properties:
        notificationId:
          type: integer
          format: int64
        channelId:
          type: string
    NotifiedTo:
      type: object
      properties:
        notifiedToId:
          $ref: '#/components/schemas/NotifiedToId'
        viewedOn:
          type: string
          format: date-time
        isViewed:
          type: boolean
        notificationsModel:
          $ref: '#/components/schemas/Notifications'
    NotifiedToId:
      type: object
      properties:
        notificationId:
          type: integer
          format: int64
        notifiedTo:
          type: string
    Channel:
      type: object
      properties:
        id:
          type: string
    NotificationGroup:
      type: object
      properties:
        id:
          type: string
        notificationGroup:
          $ref: '#/components/schemas/NotificationGroup'
        isRmTag:
          type: boolean
    NotificationTypeChannelId:
      type: object
      properties:
        typeId:
          type: integer
          format: int64
        channelId:
          type: string
    NotificationTypesChannel:
      type: object
      properties:
        notificationTypeChannelId:
          $ref: '#/components/schemas/NotificationTypeChannelId'
        contextTemplate:
          type: string
        subjectTemplate:
          type: string
        channel:
          $ref: '#/components/schemas/Channel'
        header:
          type: string
        credentials:
          $ref: '#/components/schemas/VendorCredentials'
        otp:
          type: boolean
    Priority:
      type: object
      properties:
        id:
          type: integer
          format: int32
        value:
          type: string
    Vendor:
      type: object
      properties:
        id:
          type: string
    VendorCredentials:
      type: object
      properties:
        id:
          type: integer
          format: int64
        vendor:
          $ref: '#/components/schemas/Vendor'
        channelId:
          type: string
        config:
          $ref: '#/components/schemas/JsonNode'
    Address:
      type: object
      properties:
        '@FROM':
          type: string
        '@TO':
          type: string
        '@SEQ':
          type: string
        '@TAG':
          type: string
    DLR:
      type: object
      properties:
        '@URL':
          type: string
    SMS:
      type: object
      properties:
        '@UDH':
          type: string
        '@CODING':
          type: string
        '@TEXT':
          type: string
        '@PROPERTY':
          type: string
        '@ID':
          type: string
        ADDRESS:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    ValueFirstRequestModel:
      type: object
      properties:
        '@VER':
          type: string
        USER:
          type: object
          additionalProperties:
            type: object
        DLR:
          $ref: '#/components/schemas/DLR'
        SMS:
          type: array
          items:
            $ref: '#/components/schemas/SMS'
    FileResponse:
      type: object
      properties:
        fileName:
          type: string
        fileDownloadUri:
          type: string
        fileType:
          type: string
        size:
          type: integer
          format: int64
        fileId:
          type: string
    AirFlowNotificationAudit:
      type: object
      properties:
        createdBy:
          type: integer
          format: int64
        createdDate:
          type: string
          format: date-time
        lastModifiedBy:
          type: integer
          format: int64
        lastModifiedDate:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        content:
          $ref: '#/components/schemas/JsonNode'
        typeId:
          type: integer
          format: int64
        channelId:
          type: string
